# Generated by Django 5.0.7 on 2024-09-26 05:24

import parademgr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parademgr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name", "label"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name_plural": "Organizations"},
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=parademgr.fields.UsPhoneNumberField(max_length=14, unique=True),
        ),
    ]
