# Generated by Django 5.0.7 on 2024-07-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parademgr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name", "label"]},
        ),
        migrations.AlterModelOptions(
            name="division",
            options={"ordering": ["category", "label"]},
        ),
        migrations.AlterField(
            model_name="award",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
